/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "ai_course-detail": () => import("@/views/ai/course-detail/[id].vue"),
  ai_course: () => import("@/views/ai/course/index.vue"),
  "ai_custom-training": () => import("@/views/ai/custom-training/[id].vue"),
  "ai_error-book": () => import("@/views/ai/error-book/index.vue"),
  ai_exercise: () => import("@/views/ai/exercise/index.vue"),
  ai_history: () => import("@/views/ai/history/index.vue"),
  ai_note: () => import("@/views/ai/note/index.vue"),
  ai_orchestration: () => import("@/views/ai/orchestration/[id].vue"),
  ai_training: () => import("@/views/ai/training/index.vue"),
  ai_vocabulary: () => import("@/views/ai/vocabulary/index.vue"),
  "cut_bar-detail": () => import("@/views/cut/bar-detail/[id].vue"),
  cut_bar: () => import("@/views/cut/bar/index.vue"),
  cut_history: () => import("@/views/cut/history/index.vue"),
  cut_inventory: () => import("@/views/cut/inventory/index.vue"),
  "cut_plane-detail": () => import("@/views/cut/plane-detail/[id].vue"),
  cut_plane: () => import("@/views/cut/plane/index.vue"),
  "cut_product": () => import("@/views/cut/product/index.vue"),
  home: () => import("@/views/home/index.vue"),
  lottery: () => import("@/views/lottery/[id].vue"),
  share: () => import("@/views/share/[token].vue"),
  "system_agent-studio": () => import("@/views/system/agent-studio/index.vue"),
  "system_ai-config": () => import("@/views/system/ai-config/index.vue"),
  "system_audit-log": () => import("@/views/system/audit-log/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_dashboard: () => import("@/views/system/dashboard/index.vue"),
  system_job: () => import("@/views/system/job/index.vue"),
  system_lottery: () => import("@/views/system/lottery/index.vue"),
  system_mcp: () => import("@/views/system/mcp/index.vue"),
  "system_model-scenario": () => import("@/views/system/model-scenario/index.vue"),
  system_permission: () => import("@/views/system/permission/index.vue"),
  system_skill: () => import("@/views/system/skill/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  tool_backtest: () => import("@/views/tool/backtest/index.vue"),
  tool_calendar: () => import("@/views/tool/calendar/index.vue"),
  tool_macro: () => import("@/views/tool/macro/index.vue"),
  "tool_stock-alert": () => import("@/views/tool/stock-alert/index.vue"),
  tool_stockdetail: () => import("@/views/tool/stockdetail/index.vue"),
  tool_stockscreen: () => import("@/views/tool/stockscreen/index.vue"),
  tool_watchlist: () => import("@/views/tool/watchlist/index.vue"),
  user_document: () => import("@/views/user/document/index.vue"),
  user_portrait: () => import("@/views/user/portrait/index.vue"),
  user_profile: () => import("@/views/user/profile/index.vue"),
};
