/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai',
    path: '/ai',
    component: 'layout.base',
    meta: {
      title: 'ai',
      i18nKey: 'route.ai',
      icon: 'mdi:robot-outline',
      order: 2
    },
    children: [
      {
        name: 'ai_course',
        path: '/ai/course',
        component: 'view.ai_course',
        meta: {
          title: 'ai_course',
          i18nKey: 'route.ai_course',
          icon: 'mdi:book-education',
          permissions: ['ai:course:view'],
          order: 5,
          keepAlive: true
        }
      },
      {
        name: 'ai_course-detail',
        path: '/ai/course-detail/:id',
        component: 'view.ai_course-detail',
        meta: {
          title: 'ai_course-detail',
          i18nKey: 'route.ai_course-detail',
          permissions: ['ai:course:view'],
          hideInMenu: true
        }
      },
      {
        name: 'ai_custom-training',
        path: '/ai/custom-training/:id',
        component: 'view.ai_custom-training',
        meta: {
          title: 'ai_custom-training',
          i18nKey: 'route.ai_custom-training',
          permissions: ['ai:custom-training:view'],
          hideInMenu: true,
          keepAlive: true
        }
      },
      {
        name: 'ai_error-book',
        path: '/ai/error-book',
        component: 'view.ai_error-book',
        meta: {
          title: 'ai_error-book',
          i18nKey: 'route.ai_error-book',
          icon: 'mdi:book-alert-outline',
          permissions: ['ai:error-book:view'],
          order: 7
        }
      },
      {
        name: 'ai_exercise',
        path: '/ai/exercise',
        component: 'view.ai_exercise',
        meta: {
          title: 'ai_exercise',
          i18nKey: 'route.ai_exercise',
          permissions: ['ai:chat:view'],
          hideInMenu: true,
          keepAlive: true
        }
      },
      {
        name: 'ai_history',
        path: '/ai/history',
        component: 'view.ai_history',
        meta: {
          title: 'ai_history',
          i18nKey: 'route.ai_history',
          icon: 'mdi:history',
          permissions: ['ai:history:view'],
          order: 8
        }
      },
      {
        name: 'ai_note',
        path: '/ai/note',
        component: 'view.ai_note',
        meta: {
          title: 'ai_note',
          i18nKey: 'route.ai_note',
          icon: 'mdi:notebook-outline',
          permissions: ['ai:note:view'],
          order: 7
        }
      },
      {
        name: 'ai_orchestration',
        path: '/ai/orchestration/:id',
        component: 'view.ai_orchestration',
        meta: {
          title: 'ai_orchestration',
          i18nKey: 'route.ai_orchestration',
          hideInMenu: true,
          keepAlive: true
        }
      },
      {
        name: 'ai_training',
        path: '/ai/training',
        component: 'view.ai_training',
        meta: {
          title: 'ai_training',
          i18nKey: 'route.ai_training',
          icon: 'mdi:school-outline',
          order: 1,
          keepAlive: true
        }
      },
      {
        name: 'ai_vocabulary',
        path: '/ai/vocabulary',
        component: 'view.ai_vocabulary',
        meta: {
          title: 'ai_vocabulary',
          i18nKey: 'route.ai_vocabulary',
          icon: 'mdi:book-open-outline',
          permissions: ['ai:vocabulary:view'],
          order: 6
        }
      }
    ]
  },
  {
    name: 'cut',
    path: '/cut',
    component: 'layout.base',
    meta: {
      title: 'cut',
      i18nKey: 'route.cut',
      icon: 'mdi:scissors-cutting',
      order: 4,
      permissions: ['cut:menu:view']
    },
    children: [
      {
        name: 'cut_bar',
        path: '/cut/bar',
        component: 'view.cut_bar',
        meta: {
          title: 'cut_bar',
          i18nKey: 'route.cut_bar',
          icon: 'mdi:angle-acute',
          order: 1,
          permissions: ['cut:bar:compute'],
          keepAlive: true
        }
      },
      {
        name: 'cut_bar-detail',
        path: '/cut/bar-detail/:id',
        component: 'view.cut_bar-detail',
        meta: {
          title: 'cut_bar-detail',
          i18nKey: 'route.cut_bar-detail',
          hideInMenu: true,
          permissions: ['cut:bar:compute']
        }
      },
      {
        name: 'cut_history',
        path: '/cut/history',
        component: 'view.cut_history',
        meta: {
          title: 'cut_history',
          i18nKey: 'route.cut_history',
          icon: 'mdi:history',
          order: 4,
          permissions: ['cut:record:view']
        }
      },
      {
        name: 'cut_inventory',
        path: '/cut/inventory',
        component: 'view.cut_inventory',
        meta: {
          title: 'cut_inventory',
          i18nKey: 'route.cut_inventory',
          icon: 'mdi:package-variant-closed',
          order: 3,
          permissions: ['cut:record:view']
        }
      },
      {
        name: 'cut_plane',
        path: '/cut/plane',
        component: 'view.cut_plane',
        meta: {
          title: 'cut_plane',
          i18nKey: 'route.cut_plane',
          icon: 'mdi:grid-large',
          order: 2,
          permissions: ['cut:plane:compute'],
          keepAlive: true
        }
      },
      {
        name: 'cut_plane-detail',
        path: '/cut/plane-detail/:id',
        component: 'view.cut_plane-detail',
        meta: {
          title: 'cut_plane-detail',
          i18nKey: 'route.cut_plane-detail',
          hideInMenu: true,
          permissions: ['cut:plane:compute']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'lottery',
    path: '/lottery/:id',
    component: 'layout.blank$view.lottery',
    props: true,
    meta: {
      title: 'lottery',
      i18nKey: 'route.lottery',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'share',
    path: '/share/:token',
    component: 'layout.blank$view.share',
    props: true,
    meta: {
      title: 'share',
      i18nKey: 'route.share',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 5,
      permissions: ['sys:menu:view']
    },
    children: [
      {
        name: 'system_agent-studio',
        path: '/system/agent-studio',
        component: 'view.system_agent-studio',
        meta: {
          title: 'system_agent-studio',
          i18nKey: 'route.system_agent-studio',
          icon: 'mdi:sitemap-outline',
          permissions: ['system:orchestration:view'],
          order: 9
        }
      },
      {
        name: 'system_ai-config',
        path: '/system/ai-config',
        component: 'view.system_ai-config',
        meta: {
          title: 'system_ai-config',
          i18nKey: 'route.system_ai-config',
          permissions: ['system:ai-provider:view', 'system:ai-model:view', 'system:ai-tool:view'],
          icon: 'mdi:robot-confused-outline'
        }
      },
      {
        name: 'system_audit-log',
        path: '/system/audit-log',
        component: 'view.system_audit-log',
        meta: {
          title: 'system_audit-log',
          i18nKey: 'route.system_audit-log',
          icon: 'mdi:shield-check-outline',
          permissions: ['system:audit:view'],
          order: 10
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config',
          icon: 'mdi:tune-variant',
          permissions: ['R_SUPER']
        }
      },
      {
        name: 'system_dashboard',
        path: '/system/dashboard',
        component: 'view.system_dashboard',
        meta: {
          title: 'system_dashboard',
          i18nKey: 'route.system_dashboard',
          icon: 'mdi:view-dashboard-outline',
          permissions: ['system:dashboard:view'],
          order: 1
        }
      },
      {
        name: 'system_job',
        path: '/system/job',
        component: 'view.system_job',
        meta: {
          title: 'system_job',
          i18nKey: 'route.system_job',
          icon: 'mdi:clock-outline',
          permissions: ['job:manage'],
          order: 7
        }
      },
      {
        name: 'system_lottery',
        path: '/system/lottery',
        component: 'view.system_lottery',
        meta: {
          title: 'system_lottery',
          i18nKey: 'route.system_lottery',
          icon: 'mdi:gift',
          permissions: ['lottery:activity:view']
        }
      },
      {
        name: 'system_model-scenario',
        path: '/system/model-scenario',
        component: 'view.system_model-scenario',
        meta: {
          title: 'system_model-scenario',
          i18nKey: 'route.system_model-scenario',
          icon: 'mdi:lightbulb-on-outline',
          permissions: ['model_scenario:view'],
          order: 6,
          keepAlive: true
        }
      },
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          title: 'system_permission',
          i18nKey: 'route.system_permission',
          icon: 'mdi:shield-key-outline',
          permissions: ['system:permission:view']
        }
      },
      {
        name: 'system_skill',
        path: '/system/skill',
        component: 'view.system_skill',
        meta: {
          title: 'system_skill',
          i18nKey: 'route.system_skill',
          icon: 'mdi:puzzle-outline',
          permissions: ['system:skill:view'],
          order: 8
        }
      },
      {
        name: 'system_mcp',
        path: '/system/mcp',
        component: 'view.system_mcp',
        meta: {
          title: 'system_mcp',
          i18nKey: 'route.system_mcp',
          icon: 'mdi:server-network-outline',
          permissions: ['system:mcp:manage'],
          order: 9
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-cog-outline',
          permissions: ['system:user:list']
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      icon: 'mdi:tools',
      order: 3
    },
    children: [
      {
        name: 'tool_backtest',
        path: '/tool/backtest',
        component: 'view.tool_backtest',
        meta: {
          title: 'tool_backtest',
          i18nKey: 'route.tool_backtest',
          icon: 'mdi:chart-bar',
          permissions: ['stock:screen:view']
        }
      },
      {
        name: 'tool_calendar',
        path: '/tool/calendar',
        component: 'view.tool_calendar',
        meta: {
          title: 'tool_calendar',
          i18nKey: 'route.tool_calendar',
          icon: 'mdi:calendar-month-outline',
          order: 10
        }
      },
      {
        name: 'tool_macro',
        path: '/tool/macro',
        component: 'view.tool_macro',
        meta: {
          title: 'tool_macro',
          i18nKey: 'route.tool_macro',
          icon: 'mdi:bank-outline',
          permissions: ['stock:macro:view'],
          order: 13
        }
      },
      {
        name: 'tool_stock-alert',
        path: '/tool/stock-alert',
        component: 'view.tool_stock-alert',
        meta: {
          title: 'tool_stock-alert',
          i18nKey: 'route.tool_stock-alert',
          icon: 'mdi:bell-outline',
          permissions: ['stock:watchlist:view']
        }
      },
      {
        name: 'tool_stockdetail',
        path: '/tool/stockdetail',
        component: 'view.tool_stockdetail',
        meta: {
          title: 'tool_stockdetail',
          i18nKey: 'route.tool_stockdetail',
          permissions: ['stock:menu:view'],
          hideInMenu: true,
          activeMenu: 'tool_stockscreen'
        }
      },
      {
        name: 'tool_stockscreen',
        path: '/tool/stockscreen',
        component: 'view.tool_stockscreen',
        meta: {
          title: 'tool_stockscreen',
          i18nKey: 'route.tool_stockscreen',
          icon: 'mdi:chart-line',
          permissions: ['stock:screen:view']
        }
      },
      {
        name: 'tool_watchlist',
        path: '/tool/watchlist',
        component: 'view.tool_watchlist',
        meta: {
          title: 'tool_watchlist',
          i18nKey: 'route.tool_watchlist',
          icon: 'mdi:star-outline',
          permissions: ['stock:watchlist:view']
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'mdi:account-outline',
      order: 99
    },
    children: [
      {
        name: 'user_portrait',
        path: '/user/portrait',
        component: 'view.user_portrait',
        meta: {
          title: 'user_portrait',
          i18nKey: 'route.user_portrait',
          icon: 'mdi:account-details-outline'
        }
      },
      {
        name: 'user_document',
        path: '/user/document',
        component: 'view.user_document',
        meta: {
          title: 'user_document',
          i18nKey: 'route.user_document',
          icon: 'mdi:file-document-multiple-outline'
        }
      },
      {
        name: 'user_profile',
        path: '/user/profile',
        component: 'view.user_profile',
        meta: {
          title: 'user_profile',
          i18nKey: 'route.user_profile',
          icon: 'mdi:account-circle-outline'
        }
      }
    ]
  }
];
